<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [1]:
import numpy as np

[1 1 1] [3 3 3]


In [7]:
#1 Ваш код здесь

import numpy as np

a,b = [1,1,1], [3,3,3]

arrA = np.array(a)
arrB = np.array(b)

sub = np.subtract(arrB,arrA)
div = np.divide(arrB, 2)
mult = np.multiply(sub, div)

res = np.multiply(mult, -1)
print(res)

[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [16]:
#2. Ваш код здесь

import numpy as np

chessDesk = np.zeros((8,8))
chessDesk[0, :] = [-4., -3., -2., -6., -5., -2., -3., -4.]
chessDesk[1, :] = -1
chessDesk[6, :] = 1
chessDesk[7, :] = [4., 3., 2., 6., 5., 2., 3., 4.]
print(chessDesk)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [19]:
# 3. Ваш код здесь

import numpy as np
    
arr = np.arange(2,21,2)
arr2 = arr + 1
res = arr*arr2
print(res)

[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [41]:
# 4. Ваш код здесь

from numpy import random

arr = random.uniform(0, 20, size=(4,7))
max = arr.max()
min = arr.min()
normalize = (arr- min)/(max-min)
print(np.round(normalize, 4))

[[0.4931 0.5437 0.     0.921  0.6089 0.4129 0.3843]
 [0.6266 0.7358 0.5853 0.2007 0.828  0.9371 0.3764]
 [0.0413 0.1088 0.346  0.8448 0.0851 0.1901 0.3269]
 [0.4187 0.0209 0.7793 1.     0.4301 0.7689 0.2655]]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [44]:
# 5. Ваш код здесь

import numpy as np

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

print(my_array[1:4, 1:4])



[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [48]:
# 6. Ваш код здесь

import math
import numpy as np

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

my_sin = np.sin(my_array)
print(my_sin)

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [66]:
# 7. Ваш код здесь

arr = np.random.randint(0,100,(20,1))
second_val = arr[1,0]
print(arr)
x = np.where(arr == second_val)
print(f"index: {x}, value: {second_val}")

[[92]
 [11]
 [ 8]
 [63]
 [ 0]
 [94]
 [77]
 [ 2]
 [69]
 [97]
 [16]
 [71]
 [ 3]
 [21]
 [97]
 [55]
 [67]
 [93]
 [50]
 [72]]
index: (array([1], dtype=int64), array([0], dtype=int64)), value: 11


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [2]:
# 8. Ваш код здесь

import numpy as np
from numpy import random

ar1 = random.randint(0,10, (4, 7))
ar2 = random.randint(0,10, (4,7))

res1_arr= np.maximum(ar1, ar2)
res2_arr = np.minimum(ar1, ar2)
res3_arr = (res1_arr+res2_arr)/2

print(res1_arr)
print(res2_arr)
print(res3_arr)

[[9 4 9 2 8 6 3]
 [5 8 5 9 7 4 5]
 [7 5 4 8 9 3 3]
 [4 8 9 2 6 5 6]]
[[8 4 9 0 7 4 0]
 [1 6 3 3 5 2 4]
 [3 4 0 4 6 1 0]
 [1 1 3 1 0 0 4]]
[[8.5 4.  9.  1.  7.5 5.  1.5]
 [3.  7.  4.  6.  6.  3.  4.5]
 [5.  4.5 2.  6.  7.5 2.  1.5]
 [2.5 4.5 6.  1.5 3.  2.5 5. ]]


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [3]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

filter_arr = great_array > 50
newarr = great_array[filter_arr]
sum_arr = np.sum(great_array)

print(sum_arr)



7829.945405623573


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [4]:
# 10. Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

res_arr = great_array.reshape(-1)
print(res_arr[150])

7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [5]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь

res_arr = np.where(A==B)
print(res_arr)


(array([1, 3, 5, 7], dtype=int64),)


<p style="font-size:125%; color:#119988; background-color:#transparent">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [10]:
# 12.  Ваш код здесь

import numpy as np

array = np.arange(2,21,2)
array_odd = array+1
unite = array+array_odd

mult = np.stack((array, array_odd, unite), axis = 1)

print(mult)


[[ 2  3  5]
 [ 4  5  9]
 [ 6  7 13]
 [ 8  9 17]
 [10 11 21]
 [12 13 25]
 [14 15 29]
 [16 17 33]
 [18 19 37]
 [20 21 41]]
